import { Area } from '../types/area.type';
import { NatureClassDigesto } from '../types/nature-class-digesto.type';
import { AttachmentInterface } from './attachment.interface';
import { AudienceInterface } from './audience.interface';
import { MovementInterface } from './movement.interface';
import { PartsInterface } from './parts.interface';
import { RelatedProcessInterface } from './related-process.interface';

export interface CnjInterface {
  regionalCnj: boolean | null;
  alternativeNumber: string;
  role: string;
  natureId: number;
  rod: string;
  natureClass: string;
  roleId: number;
  movements: MovementInterface[];
  distributionType: string;
  situation: string | null;
  jugde: string | null;
  area: Area;
  extraSubject: string;
  injunction: boolean | null;
  audiences: AudienceInterface[];
  originalRod: string;
  free: boolean | null;
  value: number | null;
  attachments: AttachmentInterface[];
  updateDate: string;
  systemFont: string;
  forum: string;
  situationId: number | null;
  verdictDate: string | null;
  instance: number;
  relatedProcesses: RelatedProcessInterface[];
  number: string;
  customs: unknown[];
  flag: boolean;
  judicialDistrictCnj: string;
  judicialDistrict: string;
  tribunalId: number;
  natureClassDigesto: NatureClassDigesto;
  forumCnj: string;
  tribunal: string;
  areaId: number;
  processId: number;
  distributionDate: string;
  hasSecretJustice: boolean;
  isFiled: boolean;
  classes: string[];
  access: string[];
  uf: string;
  createDate: string;
  parts: PartsInterface[];
  polo: boolean;
}
